### ISSUE TITLE
Help required with matrix questions in Java 

### ISSUE THREAD

**Issue by AnshSharma29** [AnshSharma29/JAVA-beginner-programs#1]
The questions are as follows-
Q1. WAP to create 2 x 2 matrix and display the sum. Accept the matrix from the user.

Q2. WAP to accept a 3 x 3 matrix from the user and display the left diagonal elements only.

The codes should use Scanner sc with it and should be of beginner level.

Please help me with these problems

**Comment by Kanishkrawatt** [comment]
hey, @AnshSharma29  I would like to work on this issue
